### ISSUE TITLE
Initial Comments on timing model (Intro)

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Guidelines-TimingModel#13]
The playback of a static MPD SHALL NOT depend on the mapping of the MPD timeline to real time. A client MAY play any part of the presentation at any time.

_static MPDs are not defined. It is also unclear what this requirements does_  

The MPD timeline of a dynamic MPD SHALL have a fixed mapping to real time, with each point on the timeline corresponding to a point in real time. Clients MAY introduce an additional offset with respect to real time to the extent allowed by the time shift signaling in the MPD.

_dynamic MPD not defined. You mean dynamic Media Presentation? I am ok with the basic introduction, but no shall needed_

The zero point in the MPD timeline of a dynamic MPD SHALL be mapped to the point in real time indicated by MPD@availabilityStartTime. This value SHALL NOT change between MPD updates.

_unclear what the zero point is? MPD@availabilityStartTime is just an anchor, it has no specific meaning and only operates together with Period@start_

**Comment by sandersaares** [comment]
> static MPDs are not defined. It is also unclear what this requirements does

Text has been adjusted for clarity and "static MPDs" term removed.

> dynamic MPD not defined. You mean dynamic Media Presentation? I am ok with the basic introduction, but no shall needed

Agreed and fixed.

> unclear what the zero point is? MPD@availabilityStartTime is just an anchor, it has no specific meaning and only operates together with Period@start

I believe this has been addressed already in a parllel thread.
