### ISSUE TITLE
Figure 1

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#16]
Change 
H.264 to "video codecs (H.264/AVC, H.265/HEVC, ..)"

Add "audio codecs (AAC, HE-AAC, ...)

Change "IMSC" to "subtitle formats (IMSC1, WebVTT, ...)"

**Comment by sandersaares** [comment]
This is not really meant to be a comprehensive list but okay sure why not.
