### ISSUE TITLE
Period Connectivity Definition Consistency

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/Guidelines-TimingModel#2]
In defining period connectivity we state that the adaptation set is where you place the supplemental property descriptor signalling the period connectivity between representations. This seems to conflict with the definition of period connectivity in MPEG which states connectivity as a property of Adaptation Sets.

Logically it should be okay to extend connectivity to a Representation level, but would that not mean we need to signal the descriptor within the Representation instead of the AdaptationSet?

**Comment by sandersaares** [comment]
Indeed, you are right. Given that MPEG defines this as an adaptation set level property, I suppose the timing model needs to be updated to conform.

Edit: Hmm, do I read it right that while MPEG defines it as adaptation set level property, it really still applies to representations? That is, nothing forbids having non-connected representations in adaptation sets marked with connected - the connectedness just does not apply if the representations have no match in the partner adaptation set?

**Comment by haudiobe** [comment]
(IOP 2019/11/25) It is an Adaptation Set level constraint. But you can push it to Representation if the id is the same. It is implicit that every Representation needs to be connected.

**Comment by technogeek00** [comment]
Reading again I agree that the implication is connectivity of Representations, this makes sense from the context of what an AdaptationSet would be signalling. It would seem the only case in which a representation is not connected in a signalled adaptation set is when either the representation didn't exist in the previous period or the representation doesn't exist in the new period. Which makes sense from one of the reasonings given for Period splits in the MPEG connectivity section.

From the perspective of the timing IOP, I think then the document is correct and this issue can be directly closed. @sandersaares would you agree?

**Comment by sandersaares** [comment]
> when either the representation didn't exist in the previous period or the representation doesn't exist in the new period. 

Given the comments in the call that the intent is to maintain adaptation set connectivity, I think we can follow suit and restrict usage of this feature to adaptation set level (hopefully MPEG will also clarify accordingly).

When I think of client side interactions with things like bitstream switching, I get the feeling that limiting representations to always match in full set will avoid opening some cans of worms.

If new representations need to be added or removed on the fly, this can be accomplished by usign separate adaptation sets to clearly signal to clients that these should be handled separately (while still enabling switching between them using the signaling for cross-adaptationset switching).
