### ISSUE TITLE
Availability during EarilestRemovalPoint 

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#23]
"Let EarliestRemovalPoint be AvailabilityWindowEnd + MPD@minimumUpdatePeriod. Media segments that overlap or end before EarliestRemovalPoint might be considered by clients to be available at the time the MPD update is processed."

the segments after AWE are not available but their addresses are fixed and won't change. So change it to:

 Let EarliestRemovalPoint be AvailabilityWindowEnd + MPD@minimumUpdatePeriod. The references to Media segments that overlap or end before EarliestRemovalPoint can be considered by clients to be valid at the time the MPD update is processed. Note that he segments with start point after AvailabilityWindowEnd might not be available at the time of MPD update."

**Comment by sandersaares** [comment]
No further comments, so I assume all is well. Regardless, the text has undergone improvement meanwhile anyway.
