### ISSUE TITLE
suggestedPresentationDelay

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#24]
Due to various delays and processes required to create and publish media segments, it will often be the case that media segments become available with some delay, both with regard to the expected scheduling and with regard to differences between representations. The mechanism for signaling the expected delay is MPD@suggestedPresentationDelay.

MPD@suggestedPresentationDelay is not intended to signal the delay on availability of segments. It is a suggested delay for presentation. If we want to use it for this purpose, we should add a note that we are using it for this purpose.

Also 

"Services SHALL provide a suitable value for MPD@suggestedPresentationDelay to ensure that media segments that overlap the time shift window are available."

and 

Clients SHALL NOT present any samples that are entirely outside the time shift window (whether in the past or the future).

**Comment by haudiobe** [comment]
IOP 19/01/29: The statement is not correct. Please check 4.3.4.1 bullet point 5.

**Comment by sandersaares** [comment]
No more comments, so I assume all is well. Closing.
