### ISSUE TITLE
Terminology alignment with MPEG-DASH?

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#25]
Some of the terminology used in the document is not exactly aligned with MPEG-DASH. We need to decide whether we want to keep it aligned , or if differing, add a note to each new term on how relates to MPEG-DASH corresponding term.

Examples:
Segment addresses (MPEG-DASH)  vs    Segment References (here)
representation is a sequence of segments (MPEG-DASH) vs representation is a sequence of segment addresses (here)
time shift buffer vs time shift window

**Comment by sandersaares** [comment]
Lots of work done and lots of comments addressed on this topic. If anything remains, please file new issue.
