### ISSUE TITLE
Time shift buffer

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#3]
A [=dynamic MPD=] SHALL contain a [=period=] that ends at or overlaps the end point of the [=time shift buffer=], except when reaching #timing-mpd-updates-theend in which case the last [=period=] MAY end before the end of the [=time shift buffer=].

End point of the time shift buffer = now, except when reaching end of mpd. So what does this SHALL mean?

Should it be:

A [=dynamic MPD=] SHALL contain one or more [=period=]s that the accumulated timeline overlaps with [=time shift buffer=] except when reaching #timing-mpd-updates-theend in which case the last [=period=] MAY end before the end of the [=time shift buffer=].

?

**Comment by sandersaares** [comment]
> End point of the time shift buffer = now, except when reaching end of mpd. So what does this SHALL mean?

Yes, exactly that - you must cover `now` with a period, unless reaching the end of the presentation (not "the mpd"!).

The point is to signal the intent - you can't have a running (not ending) dynamic presentation where the last period does not cover `now`. The only situation that is allowed is if there will be no more content added, ever.

This is one of several places where the timing model attempts to outline that "publishing content into the past" is not interoperable and that `now` is where things happen.

**Comment by sandersaares** [comment]
Proposed resolution: no action.

Rationale: existing text is correct, proposed modification would change the intent.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. Closed
