### ISSUE TITLE
Clarify expected manifest transformation when a live event ends

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/Guidelines-TimingModel#31]
Related to: https://github.com/google/ExoPlayer/issues/4780
Version of guidelines: https://dashif.org/docs/DASH-IF-IOP-v4.2-clean.htm

This is a request to clarify the expected manifest transformation when a live event ends, specifically for the case described in Section 4.5 (MPD and Segment-based Live Service Offering).

In particular, is it expected that `minimumUpdatePeriod` will be removed from the manifest when the event has ended? Currently `minimumUpdatePeriod` is listed as a mandatory in Table 14 in 4.5.1.1, which suggests that it should not be removed. However if this is the case, how can a client determine that the manifest wont change at some point in the future? The manifest duration will be set to indicate that no further content will be appended to the manifest, but I can't see a way that the client to determine that content wont be removed from the start of the manifest. If content wont be removed from the start, I'd argue that `minimumUpdatePeriod` should be removed from the manifest to make it clear to clients that the manifest will not change. This would be consistent with the definition of `minimumUpdatePeriod` in the DASH specification, which says:

> If this attribute is not present it indicates that the MPD does not change.

Note that for the case described in Section 4.4 (Simple Live Service Offering including MPD Updates), specifically 4.4.3.1, it does say that `minimumUpdatePeriod` should be removed when the presentation is terminated. I don't see why the case described in Section 4.5 should be different in this regard.

Thoughts?

**Comment by ojw28** [comment]
From the issue I'm trying to deal with (ref'd at the top), it seems there's confusion about the latter case. Several providers we're working with are leaving `minimumUpdatePeriod` and `type=dynamic` in the manifest, even though it isn't going to change going forward. They believe this is the correct thing to do as per the guidelines. See for example:

https://github.com/google/ExoPlayer/issues/4780#issuecomment-426580657
https://github.com/google/ExoPlayer/issues/4780#issuecomment-426882421

These are comments from one provider, but I'm aware of at least one other major streaming provider who are doing the same thing.

Perhaps the problem is that if a provider simply views their stream as a live stream that's ended (for example because their UI doesn't provide access to the stream as an on-demand stream - so they don't really consider that as a use case they provide), then they're probably not even going to read section 4.6. The start of that section describes it as being specific to the scenario of wanting to offer the content as on-demand. Furthermore it's confusing that section 4.4 describes what happens when the presentation is terminated, but section 4.5 omits to do so for the more advanced case.

I would suggest that either:

* Sections 4.4 and 4.5 should both clearly define what should happen upon termination, for both of the scenarios you mention.
* If what should happen is the same for both sections, neither section 4.4 or 4.5 should define what should happen, and there should be a subsequent section that defines what should happen upon termination that 4.4 and 4.5 can both refer to. This section should not be under the guise of a particular use case (e.g. offering up live content as on-demand), but rather as a section describing the fundamental transformation that should happen upon termination, so that it's clear a provider should implement what's described regardless of what use cases they support.

**Comment by sandersaares** [comment]
No further comments received in some time, so closing. This is now integrated into timing model document.
