### ISSUE TITLE
Correct Figure 3

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#35]
update the Figure to correct for the following: 

CMAF fragment (not segment) maps to DASH segment
Add the corresponding ISOBMFF concepts in the table 
Sidx is also defined in CMAF

**Comment by sandersaares** [comment]
> CMAF fragment (not segment) maps to DASH segment

My understanding is that the only difference between CMAF fragment and CMAF segment is that segments are addressable things and fragments are merely data, with 1 segment also being able to contain multiple fragments. Do you agree?

DASH segments are addressable (even though the address may be a byte range), so I would consider them a match for CMAF segment. Do you see a better rationale to follow?

DASH profile for CMAF equates DASH segments to CMAF fragments but also seems not to make a distinction between DASH segments and DASH subsegments, which confuses the matter. I filed a related https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/392 to discuss the profile.

>  Add the corresponding ISOBMFF concepts in the table

Which exactly would those be? I will be happy to fill some blanks if you can outline the best match for them.

>  Sidx is also defined in CMAF

I found only a single reference to the term in CMAF 2018, chapter 7.3.3.3 but no definition. What exactly is the definition you refer to here?

**Comment by RufaelDev** [comment]
- yes I was following the CMAF DASH binding its ok to rediscuss this in a new issue
- For Figure 3 you may need some more text to describe the ISOBMFF equivalents, 
  CMAF Header -> FileTypeBox + MovieBox
  CMAF Fragment -> ISOBMFF segment containing one or more movie fragments
- sidx in cmaf is used the same way as in isobmff files, sidx many other isobmff boxes 
  are not adopted in cmaf at all

**Comment by sandersaares** [comment]
The definitions you suggest for figure 3 appear to be more constrained than DASH/CMAF define (e.g. CMAF header is a lot more loosely defined), so I would rather leave them blank to avoid confusing readers by giving conflicting definitions. The main purpose of this table is to point out potential surprises in terminology, so it is not really intended to be a thorough reference. Anyone wanting more details can just reference the standards already linked in the table.

Proposed resolution: close the issue

Rationale: Separate issue opened for question of DASH-CMAF mapping (https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/392); no changes needed to table.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. Closed
