### ISSUE TITLE
Define the MPD Timeline better

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#36]
The MPD timeline is "defined" in section 5.2. a mapping is described but it is not described in detail, please define or refer to the appropriate definition in DASH or provide it, it is not clearly given in the section. Examples might be useful aswell.

**Comment by sandersaares** [comment]
Chapter "Presentation timing characteristics" added to try better explain it. How does that look?

I will also try to add some examples.

**Comment by sandersaares** [comment]
Added an example and a few more cross-references in this doc and to MPEG documents. Please inform if something more you think should be done, and propose changes if possible.

I also echo the comment from a related issue that the text is meant for reading as a single unit; that is, it is not intended that looking only at MPD timeline chapter will tell the reader everything about MPD timeline - it just introduces the concept, with following chapters building more substance upon the introduction.

**Comment by RufaelDev** [comment]
My preference would be to use the same definition as used in the MPEG DASH specification. This would be **media presentation timeline** and not **MPD timeline**. What is important is that the any key terms/concepts are defined in MPEG DASH. If an important concept is defined in this spec instead of DASH it should probably be contributed back to MPEG ti update MPEG DASH.  Consider changing MPD Timeline to Media Presentation Timeline and perhaps als importing the definition from MPEG DASH.

**Comment by sandersaares** [comment]
The difference in terms is quite intentional, as there are some unfortunate ambiguities and confusing terms in MPEG DASH. Sometimes the same term is used in two subtly different meanings, etc. These guidelines attempt to explain the concepts in ways more easily understood. However, this also requires some breaks from MPEG DASH terms.

If you or any other MPEG contributor wishes to take this feedback to MPEG and to clarify matters there, please feel free to do so. At the moment, I do not think anyone is doing that. My own activites are also scoped only to DASH-IF guidelines at the moment (largely to conserve time/effort).

**Comment by RufaelDev** [comment]
Yes, Thomas or myself should be able to help with this. A step would be 
- Discuss the differences in IOP and make sure the difference will be submitted to MPEG, make sure that everyone is on the same page with this
- Use the MPEG terminology but detail the differences with that definition and add a note that this will be contributed to MPEG

**Comment by sandersaares** [comment]
Proposed resolution: close issue with no action for v5. Review topic after v5 has been published to see what confusing aspects arise in real world usage, so points of confusion can be explicitly clarified.

Rationale: the new terms are deliberate and intended to clarify understanding of DASH to a reader. They present existing DASH timing concepts in a more easily understandable light. Using MPEG terminology would not fulfill this goal. Many references have been added to recent revisions of the text to relate to MPEG terms and clauses so readers can (if they wish) understand the mapping closer.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. Close issue
