### ISSUE TITLE
sample timeline

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#39]
Consider moving this chapter up to earlier in the document, elaborate why is it different from the mpd timeline and wallclock timeline and how the metadata is acquired to account for these differences ?

**Comment by sandersaares** [comment]
Moved up a bit and adjusted content for clarity. Created subchapter "Referencing media segments" to better outline how segments relate to the sample timeline (and to reference addressing modes). Difference from MPD timeline seems well enough elucidated by latest draft of the chapter now. Relation with wall clock time is defined via relating MPD timeline with wall clock time in "Presentation timing characteristics" chapter.

I'll close this as fixed but feel free to speak up if something in particular remains unclear in the latest revision.
