### ISSUE TITLE
5.2.7.5.2. Removing content from the MPD

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/Guidelines-TimingModel#4]
Is removal of the first period allowed in case none of its segments are available (i.e., are older than their availability start time + `@timeshiftBuffer`?

**Comment by sandersaares** [comment]
I have integrated the last statement "If all content is expired, it should be a 404" into the timing model document.

**Comment by sandersaares** [comment]
Given lack of additional comments, I close this issue as resolved (text was clarified).
