### ISSUE TITLE
inband events and timing model

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Guidelines-TimingModel#43]
define the role of inband events and the timing model, such as signalling mpd expiration by an inband event.

**Comment by sandersaares** [comment]
Latest version of the text has some references to the inband signaling chapters of DASH. There was more text in earlier drafts but it ended up being rather repeating what DASH already says, so got removed in intermediate updates.

Do you see any particularly valuable implementation guidelines on this topic that we should describe? Something where DASH does not go into enough depth or clarity?

**Comment by RufaelDev** [comment]
When referring to updating the mpd, inband  events signalling mpd validity expiration should be mentioned. Usage of this mechanism can prevent frequent mpd downloads, hence it a good optimization to  be promoted.

**Comment by sandersaares** [comment]
Indeed. This feature is documented in the "MPD snapshot validity" and "MPD refreshes" chapters.

I assume that this satisfies your request and close the issue. If you think more references should be added, please propose something specific.
