### ISSUE TITLE
13.6.1. MPD snapshot validity

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/Guidelines-TimingModel#48]
> The value 0 for MPD@minimumUpdatePeriod indicates that the MPD has no validity after the moment it is retrieved. In such a situation, the client SHALL acquire a new MPD whenever it wants to make new media segments available (no "natural" state changes will occur due to passage of time).

MPD@minimumUpdatePeriod=0 along with presence of inband MPD Validity Expiration events means that the client needs to update the MPD only when MPD Validity Expiration event arrives.

**Comment by haudiobe** [comment]
I believe v4.3 has very clear instructions on how to use Inband Events and minimumUpdatePeriod.

 

No need to re-invent the wheel.

 

Thomas

**Comment by sandersaares** [comment]
> MPD@minimumUpdatePeriod=0 along with presence of inband MPD Validity Expiration events means that the client needs to update the MPD only when MPD Validity Expiration event arrives.

I am not sure I follow - do you mean to say that a client can continue to use an MPD with MUP=0 even after its validity duration, even when no inband message arrives to extend its validity time?

I do not see how this follows from DASH. I would expect the validity to be extended by inband messages (in every segment, if necessary). Please outline where/how DASH permits an MPD to be used for accessing content even after its validity has expired.

**Comment by ZmGorynych** [comment]
Please see sec. 4.5 of DASH-IF IOP v4.3. As @haudiobe said, it is very clear on how MUP=0 works.
What you wrote disagrees with this, in my reading.

**Comment by sandersaares** [comment]
I think I agree with you that the text disagrees with this. Specifically, in IOP v4.3 we have this statement:

> If no 'emsg' validity expiration event is included, then 11
>  • the current MPD can at least be used up to a media presentation time ept + dur 

This seems to be what implies that an MPD can be used beyond its validity period (or rather, that the validity period is somehow extended by this). It is not clear to me how this follows from DASH, however - I see no such implicit extension mentioned there.

Did I understand it right what the deviation between the texts is? Can you explain how the v4.3 text relates to what is specified in DASH?

**Comment by haudiobe** [comment]
(IOP v5 2020/03/04): Explanation to Sander. Will fix inline. You can check v4.3. Thomas sends link to where he believes this is stated.
