### ISSUE TITLE
Question about Example 10

### ISSUE THREAD

**Issue by panpawel88** [Dash-Industry-Forum/Guidelines-TimingModel#52]
Hello,

I have a question about Example 10, which starts with following description:
> The example defines a sample timeline with a timescale of 1000 units per second, **with the period starting at position 900**

... and contains following MPD:
> \<MPD xmlns="urn:mpeg\:dash\:schema:mpd:2011"\>
  **\<Period duration="PT900S"\>**

I cannot understand why the period starts at position 900. _Period@start_ is not defined and there is no previous periods.

Could you clarify why in the Example 10, the period starts at position 900?

**Comment by sandersaares** [comment]
The example is correct but perhaps confusingly crafted. I will attempt to improve it.

As for the reason, the example tries to say that the period starts at position 900 **on the sample timeline** (because presentationTimeOffset is 900). On the MPD timeline, it indeed starts at 0 and lasts until 900s.

The two timelines are independent and I suspect the vague wording and the use of the same numeric value 900 are causing confusion here.

**Comment by sandersaares** [comment]
I attempted to improve the wording to make it clear that this talks about the sample timeline. Please see the referenced PR above and comment on whether it looks better.

I did not change the misleading 900 and 900 as I did not have the time to double-check the math right now, but ideally this should also get done.

**Comment by panpawel88** [comment]
Thanks for explanation. You're right - I didn't spot that there are 2 different 900's in this example. I created a diagram to make sure that I understand your example correctly:

![Example10](https://user-images.githubusercontent.com/23150639/82376795-f056b000-9a22-11ea-9a7c-939e19fabc33.png)

Is my understanding correct? If yes, then maybe there is a mistake in:

> and the period end point is approximately 69 milliseconds after the segment start point of the last media segment.

Because, the last media segment start point is 900625 (225 (segments) x 4001 (duration) + 400 (first segment start point)) and the period end point is 900900, which gives us 275 milliseconds difference.

**Comment by sandersaares** [comment]
Yes, what you say looks correct.

I am not sure where that 69 came from but your logic about 275 looks sensible to me. I will correct it to say 275.

**Comment by panpawel88** [comment]
Thanks once again for clarification! PR looks good to me.
