### ISSUE TITLE
MPD validity duration

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#6]
A dynamic MPD SHALL conform to the constraints in this document not only at its moment of initial publishing but through the entire <dfn>MPD validity duration</dfn>, which is a period of `MPD@minimumUpdatePeriod` starting from the moment the MPD download is started by a client, unless overridden by [[#inband|in-band validity signaling]].

"Unless..." is true only if inband validity expiration event is supported by all client. Should we make it a SHALL?

**Comment by sandersaares** [comment]
Proposed resolution: close the issue; text was clarified to increase understandability.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. Closed
