### ISSUE TITLE
Presentation delay

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#7]
Clients SHALL constrain seeking to the [=effective time shift buffer=]. Clients SHALL NOT attempt to present [=media segments=] that fall entirely outside the [=effective time shift buffer=].

Do we want to make it SHALL or SHOULD?

We also have service description in 4th edition that allows to define the min/max/target delay. Should we use that one?

**Comment by sandersaares** [comment]
Proposed resolution: close the issue.

Rationale: SHALL seems appropriate here.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No comments received. CLosed
