### ISSUE TITLE
5.2.2. Representations

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/Guidelines-TimingModel#8]
CHANGE TO:

A representation is a sequence of segment references and a description of the samples within the referenced media segments [MPEGDASH] 5.3.1 and 5.3.5. Each representation belongs to exactly one adaptation set and to exactly one period, although a representation may be connected with a representation in another period.

Each segment reference addresses a media segment that corresponds to a specific time span on the sample timeline. Each media segment contains samples for a specific time span on the sample timeline.

Note: Simple addressing allows the actual time span of samples within a media segment to deviate from the nominal time span described in the MPD. All timing-related clauses in this document refer to the nominal timing described in the MPD unless otherwise noted.

The exact mechanism used to define segment references depends on the addressing mode used by the representation. This document requires the additional requirement to [MPEGDASH]: all representations in the same adaptation set SHALL use the same addressing mode.

As required by [MPEGDASH], in a static MPD, a representation must contain enough segment references to cover the entire time span of the period.

As required by [MPEGDASH], in a dynamic MPD, a representation must contain enough segment references to cover the time span of the period that intersects with the time shift buffer.

Note: In dynamic MPD, media segments only become available when their end point is within the availability window. It is a valid situation that a media segment is required to be referenced but is not yet available.

As [MPEGDASH] requires, a dynamic MPD must remain valid for its entire validity duration after publishing. In other words, a dynamic MPD mustsupply enough segment references to allow the time shift buffer to extend to now + MPD@minimumUpdatePeriod, where now is the current time according to the synchronized clock.

???An unnecessary segment reference is one that is not defined as required by this chapter.???

This document requires the additional following constraints:
In a static MPD, a representation SHALL NOT contain unnecessary segment references, except when using indexed addressing in which case such segment references MAY be present.

[MPEG-DASH] requires that In a dynamic MPD, a representation must contain unnecessary segment references except when any of the following applies, in which case an unnecessary segment reference may be present:

The segment reference is for future content and will eventually become necessary.

The segment reference is defined via indexed addressing.

The segment reference is defined by an <S> element that defines multiple references using S@r, some of which are necessary.

Removal of the segment reference is not allowed by content removal constraints.

[MPEGDASH] requires that there must not be gaps or overlapping media segments in a representation of any period.

This document adds the following requirements for clients:
Clients SHALL NOT present any samples from media segments that are entirely outside the period, even if such media segments are referenced.

Media segment start/end points may be unaligned with period start/end points.

This document requires the following:
If a media segment overlaps a period boundary, clients SHOULD NOT present the samples that lie outside the period and SHOULD present the samples that lie either partially or entirely within the period.

Note: In the end, which samples are presented is entirely up to the client. It may sometimes be impractical to present media segments only partially, depending on the capabilities of the client platform, the type of media samples involved and any dependencies between samples.

**Comment by sandersaares** [comment]
Proposed resolution: close the issue.

Rationale: Iraj's PR was merged and I also added many clarifications to the text to continue his work,  to better connect to underlying standards. Even if further work remains in some areas, it should be handled as separate issues with a narrower scope.

**Comment by haudiobe** [comment]
(IOPv5 20/02/05): No other comments. If no further comments are received, the issue will be closed during the next (IOPv5 20/02/12)

**Comment by haudiobe** [comment]
(IOPv5 20/02/12): No Comments received. Closed!
